/**
 * Seed state for the Poachland demo.
 *
 * Built relative to "now" so offers have live expiry windows. Internally
 * consistent with the engine's rules: cached user aggregates (trustScore,
 * ratingsCount, tradesCompleted) equal what `recomputeReputation` would
 * produce from baselines + the rating/deal records below, and badges already
 * include everything `awardBadges` would grant, so no phantom notifications
 * fire on the first mutation.
 */

import type { DBState, DealRecord, ISOPostRecord, ListingRecord, MessageRecord, Notification, Rating, ThreadRecord, UserRecord } from "./types";

function iso(msAgo: number): string {
  return new Date(Date.now() - msAgo).toISOString();
}
const HOURS = 3_600_000;
const DAYS = 24 * HOURS;

export function buildSeedState(): DBState {
  const users: UserRecord[] = [
    {
      id: "u1",
      username: "discwitch",
      displayName: "Mara Chen",
      avatar: "/images/avatar-2.jpg",
      bio: "Open div, 12 years deep. Collecting national team jerseys since 2016. Will trade almost anything for a 2019 Brute Squad game jersey.",
      location: "Boston, MA",
      favoriteTeams: ["Brute Squad", "Scandal", "Riot"],
      memberSince: iso(870 * DAYS),
      isVerified: true,
      badges: [
        { id: "b1", label: "Founding Trader", type: "founding" },
        { id: "b2", label: "First Trade", type: "first-trade" },
        { id: "b3", label: "Trusted Trader", type: "trusted" },
        { id: "b4", label: "Veteran Trader", type: "veteran" },
        { id: "b5", label: "Quick Shipper", type: "quick-shipper" },
      ],
      baselineTrades: 45,
      baselineRatingCount: 40,
      baselineRatingSum: 196.4,
      trustScore: 4.9,
      ratingsCount: 42,
      tradesCompleted: 47,
    },
    {
      id: "u2",
      username: "flick_therapy",
      displayName: "Jake Torres",
      avatar: "/images/avatar-1.jpg",
      bio: "Midwest club open. Hoarder of tournament discs. Ask me about my 2011 UPA Championship disc.",
      location: "Chicago, IL",
      favoriteTeams: ["Johnny Bravo", "Ring of Fire", "Machine"],
      memberSince: iso(730 * DAYS),
      isVerified: true,
      badges: [
        { id: "b6", label: "First Trade", type: "first-trade" },
        { id: "b7", label: "Trusted Trader", type: "trusted" },
        { id: "b8", label: "Veteran Trader", type: "veteran" },
        { id: "b9", label: "Collector", type: "collector" },
      ],
      baselineTrades: 30,
      baselineRatingCount: 25,
      baselineRatingSum: 117.5,
      trustScore: 4.7,
      ratingsCount: 25,
      tradesCompleted: 31,
    },
    {
      id: "u3",
      username: "huck_and_pray",
      displayName: "Sam Rivera",
      avatar: "/images/avatar-3.jpg",
      bio: "Mixed div, Pacific NW. Trade stack is deep. Send offers.",
      location: "Portland, OR",
      favoriteTeams: ["Mixtape", "AMP", "Drag'n Thrust"],
      memberSince: iso(540 * DAYS),
      isVerified: false,
      badges: [
        { id: "b10", label: "First Trade", type: "first-trade" },
        { id: "b11", label: "Trusted Trader", type: "trusted" },
      ],
      baselineTrades: 17,
      baselineRatingCount: 12,
      baselineRatingSum: 54.7,
      trustScore: 4.5,
      ratingsCount: 13,
      tradesCompleted: 18,
    },
    {
      id: "u4",
      username: "sky_pilot",
      displayName: "Dana Kim",
      avatar: "/placeholder-user.jpg",
      bio: "Seattle. Cutter by trade, collector by accident. Sockeye through and through.",
      location: "Seattle, WA",
      favoriteTeams: ["Sockeye", "Riot", "Mixtape"],
      memberSince: iso(400 * DAYS),
      isVerified: true,
      badges: [{ id: "b12", label: "First Trade", type: "first-trade" }],
      baselineTrades: 8,
      baselineRatingCount: 7,
      baselineRatingSum: 33.6,
      trustScore: 4.8,
      ratingsCount: 7,
      tradesCompleted: 8,
    },
    {
      id: "u5",
      username: "zone_dee",
      displayName: "Priya Natarajan",
      avatar: "/placeholder-user.jpg",
      bio: "Austin mixed. New-ish here — building my rep one clean trade at a time.",
      location: "Austin, TX",
      favoriteTeams: ["Public Enemy", "Waterloo"],
      memberSince: iso(150 * DAYS),
      isVerified: false,
      badges: [{ id: "b13", label: "First Trade", type: "first-trade" }],
      baselineTrades: 3,
      baselineRatingCount: 3,
      baselineRatingSum: 13.8,
      trustScore: 4.6,
      ratingsCount: 3,
      tradesCompleted: 3,
    },
    {
      id: "u6",
      username: "grip_it_rip_it",
      displayName: "Cole Barnes",
      avatar: "/placeholder-user.jpg",
      bio: "Denver. Got a garage full of gear, everything's for sale.",
      location: "Denver, CO",
      favoriteTeams: ["Johnny Bravo"],
      memberSince: iso(40 * DAYS),
      isVerified: false,
      badges: [{ id: "b14", label: "First Trade", type: "first-trade" }],
      baselineTrades: 1,
      baselineRatingCount: 1,
      baselineRatingSum: 3.7,
      trustScore: 3.7,
      ratingsCount: 1,
      tradesCompleted: 1,
    },
  ];

  const listings: ListingRecord[] = [
    {
      id: "l1",
      sellerId: "u1",
      type: "jersey",
      title: "2022 Brute Squad Game Jersey — #14",
      team: "Brute Squad",
      year: "2022",
      division: "women",
      level: "club",
      size: "M",
      condition: "Near Mint",
      listingType: "trade",
      tradeFor: "Any 2019-2022 national team jersey, open to offers",
      photos: ["/images/jersey-1.jpg"],
      description:
        "Authentic game jersey, worn twice. No stains, no pulls. Sublimated Tokay design. The actual jersey worn at nationals.",
      views: 342,
      saves: 28,
      createdAt: iso(6 * DAYS),
      updatedAt: iso(6 * DAYS),
      shippingPreference: "seller-pays",
      tags: ["nationals", "brute-squad", "rare", "womens"],
      isRare: true,
      isFeatured: true,
      status: "active",
    },
    {
      id: "l2",
      sellerId: "u2",
      type: "disc",
      title: "2019 WFDF World Championship Disc — Cologne",
      team: "Team USA",
      year: "2019",
      level: "national",
      condition: "Mint",
      listingType: "sell",
      askingPrice: 65,
      photos: ["/images/disc-1.jpg"],
      description:
        "Never thrown. Straight out of the bag from Cologne worlds. Full color WFDF stamp on back. One of maybe 200 in circulation.",
      views: 218,
      saves: 41,
      createdAt: iso(9 * DAYS),
      updatedAt: iso(9 * DAYS),
      shippingPreference: "buyer-pays",
      tags: ["worlds", "wfdf", "mint", "rare"],
      isRare: true,
      isFeatured: true,
      status: "active",
    },
    {
      id: "l3",
      sellerId: "u3",
      type: "jersey",
      title: "Mixtape 2021 USAU Nationals Jersey",
      team: "Mixtape",
      year: "2021",
      division: "mixed",
      level: "club",
      size: "L",
      condition: "Good",
      listingType: "trade+cash",
      askingPrice: 20,
      tradeFor: "Mixed division jerseys, collector discs",
      photos: ["/images/jersey-2.jpg"],
      description:
        "Real game jersey from USAU Nationals in San Diego. Minor wear on hem, barely visible. Great addition to any mixed collection.",
      views: 156,
      saves: 12,
      createdAt: iso(11 * DAYS),
      updatedAt: iso(11 * DAYS),
      shippingPreference: "buyer-pays",
      tags: ["mixtape", "mixed", "nationals"],
      isRare: false,
      isFeatured: false,
      status: "active",
    },
    {
      id: "l4",
      sellerId: "u1",
      type: "jersey",
      title: "Riot 2018 Club Nationals Practice Jersey",
      team: "Riot",
      year: "2018",
      division: "women",
      level: "club",
      size: "S",
      condition: "Good",
      listingType: "sell",
      askingPrice: 35,
      photos: ["/images/jersey-3.jpg"],
      description:
        "Practice jersey from Riot's 2018 club season. Some fading from washing but all graphics intact.",
      views: 89,
      saves: 7,
      createdAt: iso(13 * DAYS),
      updatedAt: iso(13 * DAYS),
      shippingPreference: "seller-pays",
      tags: ["riot", "womens", "practice"],
      isRare: false,
      status: "active",
    },
    {
      id: "l5",
      sellerId: "u2",
      type: "disc",
      title: "2011 UPA Club Championship Disc — Sarasota",
      team: "Multiple",
      year: "2011",
      level: "club",
      condition: "Good",
      listingType: "sell",
      askingPrice: 45,
      photos: ["/images/disc-2.jpg"],
      description:
        "Vintage disc from the last year of UPA branding before USAU. Significant historical value. Some scuffs from age but fully collectible.",
      views: 304,
      saves: 33,
      createdAt: iso(16 * DAYS),
      updatedAt: iso(16 * DAYS),
      shippingPreference: "buyer-pays",
      tags: ["vintage", "upa", "historical"],
      isRare: true,
      isFeatured: true,
      status: "active",
    },
    {
      id: "l6",
      sellerId: "u3",
      type: "jersey",
      title: "AMP 2023 USAU Mixed Nationals Jersey",
      team: "AMP",
      year: "2023",
      division: "mixed",
      level: "club",
      size: "XL",
      condition: "Near Mint",
      listingType: "trade",
      tradeFor: "Open to mixed or club jerseys. Especially interested in Drag'n Thrust.",
      photos: ["/images/jersey-4.jpg"],
      description:
        "Barely worn. Worn one point in pool play as a sub. Basically a collectible at this point.",
      views: 201,
      saves: 19,
      createdAt: iso(19 * DAYS),
      updatedAt: iso(19 * DAYS),
      shippingPreference: "seller-pays",
      tags: ["amp", "mixed", "nationals", "near-mint"],
      isRare: false,
      status: "active",
    },
    {
      id: "l7",
      sellerId: "u1",
      type: "disc",
      title: "Matte Black Chain Lightning Tour Disc — 2020",
      team: "Chain Lightning",
      year: "2020",
      level: "club",
      condition: "Mint",
      listingType: "sell",
      askingPrice: 30,
      photos: ["/images/disc-3.jpg"],
      description:
        "Tour disc from Chain Lightning's 2020 campaign. Never thrown. Matte finish, neon green artwork.",
      views: 127,
      saves: 22,
      createdAt: iso(24 * DAYS),
      updatedAt: iso(24 * DAYS),
      shippingPreference: "seller-pays",
      tags: ["chain-lightning", "matte", "tour-disc"],
      isRare: false,
      status: "active",
    },
    {
      id: "l8",
      sellerId: "u2",
      type: "jersey",
      title: "Revolver 2017 Club Nationals Jersey",
      team: "Revolver",
      year: "2017",
      division: "open",
      level: "club",
      size: "M",
      condition: "Fair",
      listingType: "free",
      photos: ["/images/jersey-5.jpg"],
      description:
        "Looking to rehome this. Got two Revolver jerseys, only need one. Some pilling on back but it's real game-worn.",
      views: 512,
      saves: 44,
      createdAt: iso(27 * DAYS),
      updatedAt: iso(27 * DAYS),
      shippingPreference: "buyer-pays",
      tags: ["revolver", "open", "free", "game-worn"],
      isRare: false,
      status: "active",
    },
    {
      id: "l9",
      sellerId: "u1",
      type: "disc",
      title: "2018 Select Flight Invite Disc — Free to a Good Home",
      team: "Multiple",
      year: "2018",
      level: "tournament",
      condition: "Fair",
      listingType: "free",
      photos: ["/images/disc-2.jpg"],
      description:
        "Tournament disc from Select Flight 2018. Been in my trunk for years — deserves a shelf, not my trunk. First solid claim gets it.",
      views: 164,
      saves: 18,
      createdAt: iso(3 * DAYS),
      updatedAt: iso(3 * DAYS),
      shippingPreference: "seller-pays",
      tags: ["select-flight", "free", "tournament"],
      isRare: false,
      status: "active",
    },
    {
      id: "l10",
      sellerId: "u6",
      type: "jersey",
      title: "SIGNED Team USA Worlds Jersey — ultra rare!!",
      team: "Team USA",
      year: "2016",
      level: "national",
      size: "L",
      condition: "Mint",
      listingType: "sell",
      askingPrice: 200,
      photos: ["/images/jersey-5.jpg"],
      description:
        "Signed by the whole 2016 roster. No COA but trust me it's real. Price firm. No trades.",
      views: 77,
      saves: 3,
      createdAt: iso(2 * DAYS),
      updatedAt: iso(2 * DAYS),
      shippingPreference: "buyer-pays",
      tags: ["team-usa", "signed", "rare"],
      isRare: true,
      status: "active",
    },
    {
      id: "l11",
      sellerId: "u4",
      type: "jersey",
      title: "Sockeye 2017 Nationals Jersey — Fish Scale Design",
      team: "Sockeye",
      year: "2017",
      division: "open",
      level: "club",
      size: "L",
      condition: "Near Mint",
      listingType: "trade",
      tradeFor: "Riot or Mixtape jerseys, or a clean worlds disc",
      photos: ["/images/jersey-4.jpg"],
      description:
        "The famous fish scale sublimation. Worn for one season, washed cold, hung dry. Colors still pop.",
      views: 143,
      saves: 26,
      createdAt: iso(1 * DAYS),
      updatedAt: iso(1 * DAYS),
      shippingPreference: "seller-pays",
      tags: ["sockeye", "open", "nationals"],
      isRare: false,
      isFeatured: true,
      status: "active",
    },
    {
      id: "l12",
      sellerId: "u5",
      type: "disc",
      title: "Centex 2023 Tournament Disc",
      team: "Multiple",
      year: "2023",
      level: "college",
      condition: "Near Mint",
      listingType: "sell",
      askingPrice: 25,
      photos: ["/images/disc-1.jpg"],
      description: "College classic. Thrown maybe five times on grass. No dings.",
      views: 58,
      saves: 6,
      createdAt: iso(5 * DAYS),
      updatedAt: iso(5 * DAYS),
      shippingPreference: "buyer-pays",
      tags: ["centex", "college"],
      isRare: false,
      status: "active",
    },
    // Locked in the accepted deal d3 (u1 ⇄ u4).
    {
      id: "l13",
      sellerId: "u1",
      type: "jersey",
      title: "Fury 2019 Warmup Jersey",
      team: "Fury",
      year: "2019",
      division: "women",
      level: "club",
      size: "M",
      condition: "Good",
      listingType: "trade",
      tradeFor: "Sockeye or Riot gear",
      photos: ["/images/jersey-2.jpg"],
      description: "Fury warmup from the 2019 season. Light wear, zero damage.",
      views: 96,
      saves: 9,
      createdAt: iso(21 * DAYS),
      updatedAt: iso(2 * DAYS),
      shippingPreference: "seller-pays",
      tags: ["fury", "womens", "warmup"],
      isRare: false,
      status: "pending",
    },
    {
      id: "l14",
      sellerId: "u4",
      type: "disc",
      title: "Truck Stop 2022 Pro Championships Disc",
      team: "Truck Stop",
      year: "2022",
      level: "pro",
      condition: "Mint",
      listingType: "trade",
      tradeFor: "Women's club jerseys",
      photos: ["/images/disc-3.jpg"],
      description: "Pro champs disc, never thrown. DC represent.",
      views: 88,
      saves: 11,
      createdAt: iso(22 * DAYS),
      updatedAt: iso(2 * DAYS),
      shippingPreference: "seller-pays",
      tags: ["truck-stop", "pro"],
      isRare: false,
      status: "pending",
    },
    // History: completed trade d4 (u1 ⇄ u2).
    {
      id: "l15",
      sellerId: "u1",
      type: "jersey",
      title: "Riot 2016 Away Jersey",
      team: "Riot",
      year: "2016",
      division: "women",
      level: "club",
      size: "S",
      condition: "Good",
      listingType: "trade",
      photos: ["/images/jersey-3.jpg"],
      description: "Classic Riot away kit. Traded on.",
      views: 210,
      saves: 15,
      createdAt: iso(60 * DAYS),
      updatedAt: iso(8 * DAYS),
      shippingPreference: "seller-pays",
      tags: ["riot", "womens"],
      isRare: false,
      status: "traded",
    },
    {
      id: "l16",
      sellerId: "u2",
      type: "disc",
      title: "Machine 2019 Nationals Disc",
      team: "Machine",
      year: "2019",
      level: "club",
      condition: "Near Mint",
      listingType: "trade",
      photos: ["/images/disc-1.jpg"],
      description: "Machine nationals run, 2019. Traded on.",
      views: 130,
      saves: 8,
      createdAt: iso(58 * DAYS),
      updatedAt: iso(8 * DAYS),
      shippingPreference: "buyer-pays",
      tags: ["machine", "nationals"],
      isRare: false,
      status: "traded",
    },
    // History: completed purchase d5 (u1 bought from u3).
    {
      id: "l17",
      sellerId: "u3",
      type: "jersey",
      title: "Drag'n Thrust 2018 Nationals Jersey",
      team: "Drag'n Thrust",
      year: "2018",
      division: "mixed",
      level: "club",
      size: "M",
      condition: "Good",
      listingType: "sell",
      askingPrice: 40,
      photos: ["/images/jersey-4.jpg"],
      description: "Minneapolis mixed royalty. Sold.",
      views: 175,
      saves: 14,
      createdAt: iso(75 * DAYS),
      updatedAt: iso(30 * DAYS),
      shippingPreference: "buyer-pays",
      tags: ["dragn-thrust", "mixed"],
      isRare: false,
      status: "sold",
    },
  ];

  const isoPosts: ISOPostRecord[] = [
    {
      id: "iso1",
      userId: "u2",
      itemType: "jersey",
      description:
        "ISO: Any Sockeye jersey from 2015-2019. Will pay or trade. Been hunting for three years.",
      team: "Sockeye",
      size: "L",
      maxPrice: 80,
      createdAt: iso(4 * DAYS),
      saves: 8,
      status: "active",
    },
    {
      id: "iso2",
      userId: "u3",
      itemType: "disc",
      description:
        "Looking for a 2017 WFDF Worlds disc from Cincinnati. Will pay top dollar or trade multiple discs.",
      team: "WFDF",
      maxPrice: 120,
      createdAt: iso(5 * DAYS),
      saves: 15,
      status: "active",
    },
    {
      id: "iso3",
      userId: "u1",
      itemType: "jersey",
      description:
        "ISO: Any Scandal women's jersey, any year. Have a solid trade stack including Brute, Riot, Fury.",
      team: "Scandal",
      size: "S",
      createdAt: iso(7 * DAYS),
      saves: 11,
      status: "active",
    },
    {
      id: "iso4",
      userId: "u2",
      itemType: "disc",
      description:
        "Hunting vintage UPA era discs (pre-2013). Any condition considered. More interested in the history than the shine.",
      createdAt: iso(9 * DAYS),
      saves: 6,
      status: "active",
    },
    {
      id: "iso5",
      userId: "u4",
      itemType: "jersey",
      description:
        "ISO: Riot 2018-2020 game jerseys, size S or M. Trading from a deep Sockeye stack or paying cash.",
      team: "Riot",
      size: "M",
      maxPrice: 90,
      createdAt: iso(1 * DAYS),
      saves: 4,
      status: "active",
    },
  ];

  // ── Deals ───────────────────────────────────────────────────────────────────

  const deals: DealRecord[] = [
    // d1: OPEN — u2 proposes his UPA disc + $15 for u1's Brute Squad jersey.
    // It's u1's move: accept / counter / decline.
    {
      id: "d1",
      kind: "trade",
      listingId: "l1",
      proposerId: "u2",
      ownerId: "u1",
      offers: [
        {
          id: "of1",
          byUserId: "u2",
          proposerListingIds: ["l5"],
          ownerListingIds: ["l1"],
          cashFromProposer: 15,
          cashFromOwner: 0,
          note: "That Brute jersey is sick. Offering my 2011 UPA disc + $15 cash. Let me know.",
          createdAt: iso(2 * DAYS),
          expiresAt: iso(-5 * DAYS),
          status: "pending",
        },
      ],
      status: "open",
      threadId: "t1",
      createdAt: iso(2 * DAYS),
      updatedAt: iso(2 * DAYS),
      fulfillment: {},
    },
    // d2: OPEN, mid-negotiation — u3 proposed his Mixtape jersey for u2's UPA
    // disc; u2 countered asking for +$10. It's u3's move.
    {
      id: "d2",
      kind: "trade",
      listingId: "l5",
      proposerId: "u3",
      ownerId: "u2",
      offers: [
        {
          id: "of2",
          byUserId: "u3",
          proposerListingIds: ["l3"],
          ownerListingIds: ["l5"],
          cashFromProposer: 0,
          cashFromOwner: 0,
          note: "Mixtape jersey for your UPA disc straight up? Both Good condition. Fair trade imo.",
          createdAt: iso(3 * DAYS),
          expiresAt: iso(-4 * DAYS),
          status: "superseded",
        },
        {
          id: "of3",
          byUserId: "u2",
          proposerListingIds: ["l3"],
          ownerListingIds: ["l5"],
          cashFromProposer: 10,
          cashFromOwner: 0,
          note: "Close, but the disc books higher than the jersey. Jersey + $10 and we're done.",
          createdAt: iso(1 * DAYS),
          expiresAt: iso(-6 * DAYS),
          status: "pending",
        },
      ],
      status: "open",
      threadId: "t2",
      createdAt: iso(3 * DAYS),
      updatedAt: iso(1 * DAYS),
      fulfillment: {},
    },
    // d3: ACCEPTED — u4 ⇄ u1, in the shipping stage. u4 has shipped.
    {
      id: "d3",
      kind: "trade",
      listingId: "l13",
      proposerId: "u4",
      ownerId: "u1",
      offers: [
        {
          id: "of4",
          byUserId: "u4",
          proposerListingIds: ["l14"],
          ownerListingIds: ["l13"],
          cashFromProposer: 0,
          cashFromOwner: 0,
          note: "Truck Stop pro champs disc for the Fury warmup? Both clean.",
          createdAt: iso(4 * DAYS),
          expiresAt: iso(-3 * DAYS),
          status: "accepted",
        },
      ],
      status: "accepted",
      threadId: "t3",
      createdAt: iso(4 * DAYS),
      updatedAt: iso(1 * DAYS),
      acceptedAt: iso(2 * DAYS),
      fulfillment: {
        u4: { shippedAt: iso(1 * DAYS), tracking: "9400 1108 8422 5510 3391 07" },
      },
    },
    // d4: COMPLETED trade u2 ⇄ u1. u2 already rated u1; u1's rating is pending.
    {
      id: "d4",
      kind: "trade",
      listingId: "l15",
      proposerId: "u2",
      ownerId: "u1",
      offers: [
        {
          id: "of5",
          byUserId: "u2",
          proposerListingIds: ["l16"],
          ownerListingIds: ["l15"],
          cashFromProposer: 0,
          cashFromOwner: 0,
          note: "Machine disc for the Riot away kit?",
          createdAt: iso(14 * DAYS),
          expiresAt: iso(7 * DAYS),
          status: "accepted",
        },
      ],
      status: "completed",
      threadId: "t4",
      createdAt: iso(14 * DAYS),
      updatedAt: iso(8 * DAYS),
      acceptedAt: iso(13 * DAYS),
      completedAt: iso(8 * DAYS),
      fulfillment: {
        u1: { shippedAt: iso(12 * DAYS), receivedAt: iso(8 * DAYS) },
        u2: { shippedAt: iso(12 * DAYS), tracking: "9400 1108 8421 0042 8817 25", receivedAt: iso(9 * DAYS) },
      },
    },
    // d5: COMPLETED purchase — u1 bought u3's Drag'n Thrust jersey. Both rated.
    {
      id: "d5",
      kind: "buy",
      listingId: "l17",
      proposerId: "u1",
      ownerId: "u3",
      offers: [
        {
          id: "of6",
          byUserId: "u1",
          proposerListingIds: [],
          ownerListingIds: ["l17"],
          cashFromProposer: 40,
          cashFromOwner: 0,
          note: "Full ask, no haggle. That jersey belongs in my mixed wall.",
          createdAt: iso(35 * DAYS),
          expiresAt: iso(28 * DAYS),
          status: "accepted",
        },
      ],
      status: "completed",
      threadId: "t5",
      createdAt: iso(35 * DAYS),
      updatedAt: iso(30 * DAYS),
      acceptedAt: iso(34 * DAYS),
      completedAt: iso(30 * DAYS),
      fulfillment: {
        u1: { receivedAt: iso(30 * DAYS) },
        u3: { shippedAt: iso(33 * DAYS), receivedAt: iso(31 * DAYS) },
      },
    },
    // d6 + d7: OPEN claims on u1's free disc (l9) — u1 picks a claimant.
    {
      id: "d6",
      kind: "claim",
      listingId: "l9",
      proposerId: "u3",
      ownerId: "u1",
      offers: [
        {
          id: "of7",
          byUserId: "u3",
          proposerListingIds: [],
          ownerListingIds: ["l9"],
          cashFromProposer: 0,
          cashFromOwner: 0,
          note: "I was AT Select Flight 2018. This disc completes the story. Happy to cover shipping.",
          createdAt: iso(2 * DAYS),
          expiresAt: iso(-5 * DAYS),
          status: "pending",
        },
      ],
      status: "open",
      threadId: "t6",
      createdAt: iso(2 * DAYS),
      updatedAt: iso(2 * DAYS),
      fulfillment: {},
    },
    {
      id: "d7",
      kind: "claim",
      listingId: "l9",
      proposerId: "u5",
      ownerId: "u1",
      offers: [
        {
          id: "of8",
          byUserId: "u5",
          proposerListingIds: [],
          ownerListingIds: ["l9"],
          cashFromProposer: 0,
          cashFromOwner: 0,
          note: "Starting a college program's trophy shelf — this would be perfect for the kids.",
          createdAt: iso(1 * DAYS),
          expiresAt: iso(-6 * DAYS),
          status: "pending",
        },
      ],
      status: "open",
      threadId: "t7",
      createdAt: iso(1 * DAYS),
      updatedAt: iso(1 * DAYS),
      fulfillment: {},
    },
    // d8: DECLINED history — u5 offered her Centex disc for u1's Riot jersey.
    {
      id: "d8",
      kind: "trade",
      listingId: "l4",
      proposerId: "u5",
      ownerId: "u1",
      offers: [
        {
          id: "of9",
          byUserId: "u5",
          proposerListingIds: ["l12"],
          ownerListingIds: ["l4"],
          cashFromProposer: 0,
          cashFromOwner: 0,
          note: "Centex disc for the Riot practice jersey?",
          createdAt: iso(10 * DAYS),
          expiresAt: iso(3 * DAYS),
          status: "declined",
        },
      ],
      status: "declined",
      threadId: "t8",
      createdAt: iso(10 * DAYS),
      updatedAt: iso(9 * DAYS),
      closedAt: iso(9 * DAYS),
      declineReason: "Holding out for a jersey trade on this one, sorry!",
      fulfillment: {},
    },
  ];

  // ── Threads & messages ──────────────────────────────────────────────────────

  const threads: ThreadRecord[] = [
    { id: "t1", participantIds: ["u2", "u1"], listingId: "l1", dealId: "d1", createdAt: iso(2 * DAYS), updatedAt: iso(2 * DAYS), lastRead: { u2: iso(2 * DAYS), u1: iso(3 * DAYS) } },
    { id: "t2", participantIds: ["u3", "u2"], listingId: "l5", dealId: "d2", createdAt: iso(3 * DAYS), updatedAt: iso(1 * DAYS), lastRead: { u3: iso(2 * DAYS), u2: iso(1 * DAYS) } },
    { id: "t3", participantIds: ["u4", "u1"], listingId: "l13", dealId: "d3", createdAt: iso(4 * DAYS), updatedAt: iso(1 * DAYS), lastRead: { u4: iso(1 * DAYS), u1: iso(20 * HOURS) } },
    { id: "t4", participantIds: ["u2", "u1"], listingId: "l15", dealId: "d4", createdAt: iso(14 * DAYS), updatedAt: iso(8 * DAYS), lastRead: { u2: iso(8 * DAYS), u1: iso(8 * DAYS) } },
    { id: "t5", participantIds: ["u1", "u3"], listingId: "l17", dealId: "d5", createdAt: iso(35 * DAYS), updatedAt: iso(30 * DAYS), lastRead: { u1: iso(30 * DAYS), u3: iso(30 * DAYS) } },
    { id: "t6", participantIds: ["u3", "u1"], listingId: "l9", dealId: "d6", createdAt: iso(2 * DAYS), updatedAt: iso(2 * DAYS), lastRead: { u3: iso(2 * DAYS), u1: iso(3 * DAYS) } },
    { id: "t7", participantIds: ["u5", "u1"], listingId: "l9", dealId: "d7", createdAt: iso(1 * DAYS), updatedAt: iso(1 * DAYS), lastRead: { u5: iso(1 * DAYS), u1: iso(2 * DAYS) } },
    { id: "t8", participantIds: ["u5", "u1"], listingId: "l4", dealId: "d8", createdAt: iso(10 * DAYS), updatedAt: iso(9 * DAYS), lastRead: { u5: iso(9 * DAYS), u1: iso(9 * DAYS) } },
    // Plain listing inquiry, unread by u1.
    { id: "t9", participantIds: ["u4", "u1"], listingId: "l7", createdAt: iso(6 * HOURS), updatedAt: iso(2 * HOURS), lastRead: { u4: iso(2 * HOURS), u1: iso(5 * HOURS) } },
  ];

  const messages: MessageRecord[] = [
    // t1 / d1
    { id: "m1", threadId: "t1", senderId: "u2", kind: "offer", content: `"2011 UPA Club Championship Disc — Sarasota" + $15 ⇄ "2022 Brute Squad Game Jersey — #14"`, offerId: "of1", createdAt: iso(2 * DAYS) },
    { id: "m2", threadId: "t1", senderId: "u2", kind: "text", content: "That Brute jersey is sick. Offering my 2011 UPA disc + $15 cash. Let me know.", createdAt: iso(2 * DAYS - 60_000) },
    // t2 / d2
    { id: "m3", threadId: "t2", senderId: "u3", kind: "offer", content: `"Mixtape 2021 USAU Nationals Jersey" ⇄ "2011 UPA Club Championship Disc — Sarasota"`, offerId: "of2", createdAt: iso(3 * DAYS) },
    { id: "m4", threadId: "t2", senderId: "u3", kind: "text", content: "Mixtape jersey for your UPA disc straight up? Both Good condition. Fair trade imo.", createdAt: iso(3 * DAYS - 60_000) },
    { id: "m5", threadId: "t2", senderId: "u2", kind: "offer", content: `"Mixtape 2021 USAU Nationals Jersey" + $10 ⇄ "2011 UPA Club Championship Disc — Sarasota"`, offerId: "of3", createdAt: iso(1 * DAYS) },
    { id: "m6", threadId: "t2", senderId: "u2", kind: "text", content: "Close, but the disc books higher than the jersey. Jersey + $10 and we're done.", createdAt: iso(1 * DAYS - 60_000) },
    // t3 / d3
    { id: "m7", threadId: "t3", senderId: "u4", kind: "offer", content: `"Truck Stop 2022 Pro Championships Disc" ⇄ "Fury 2019 Warmup Jersey"`, offerId: "of4", createdAt: iso(4 * DAYS) },
    { id: "m8", threadId: "t3", senderId: "u4", kind: "text", content: "Truck Stop pro champs disc for the Fury warmup? Both clean.", createdAt: iso(4 * DAYS - 60_000) },
    { id: "m9", threadId: "t3", senderId: "u1", kind: "system", content: "discwitch accepted the offer. Deal agreed — arrange shipping and mark it complete when your end arrives.", createdAt: iso(2 * DAYS) },
    { id: "m10", threadId: "t3", senderId: "u4", kind: "system", content: "sky_pilot marked their end shipped — tracking 9400 1108 8422 5510 3391 07.", createdAt: iso(1 * DAYS) },
    { id: "m11", threadId: "t3", senderId: "u4", kind: "text", content: "Disc is in the mail! USPS says Thursday. Send the Fury when you get a chance 🙏", createdAt: iso(22 * HOURS) },
    // t4 / d4
    { id: "m12", threadId: "t4", senderId: "u2", kind: "offer", content: `"Machine 2019 Nationals Disc" ⇄ "Riot 2016 Away Jersey"`, offerId: "of5", createdAt: iso(14 * DAYS) },
    { id: "m13", threadId: "t4", senderId: "u1", kind: "system", content: "discwitch accepted the offer. Deal agreed — arrange shipping and mark it complete when your end arrives.", createdAt: iso(13 * DAYS) },
    { id: "m14", threadId: "t4", senderId: "u1", kind: "system", content: "Deal complete 🎉 Both sides confirmed. Rate each other to build trust.", createdAt: iso(8 * DAYS) },
    // t5 / d5
    { id: "m15", threadId: "t5", senderId: "u1", kind: "offer", content: `$40 for "Drag'n Thrust 2018 Nationals Jersey"`, offerId: "of6", createdAt: iso(35 * DAYS) },
    { id: "m16", threadId: "t5", senderId: "u3", kind: "system", content: "huck_and_pray accepted the offer. Deal agreed — arrange shipping and mark it complete when your end arrives.", createdAt: iso(34 * DAYS) },
    { id: "m17", threadId: "t5", senderId: "u1", kind: "system", content: "Deal complete 🎉 Both sides confirmed. Rate each other to build trust.", createdAt: iso(30 * DAYS) },
    // t6 / d6 claim
    { id: "m18", threadId: "t6", senderId: "u3", kind: "offer", content: `wants to claim "2018 Select Flight Invite Disc — Free to a Good Home"`, offerId: "of7", createdAt: iso(2 * DAYS) },
    { id: "m19", threadId: "t6", senderId: "u3", kind: "text", content: "I was AT Select Flight 2018. This disc completes the story. Happy to cover shipping.", createdAt: iso(2 * DAYS - 60_000) },
    // t7 / d7 claim
    { id: "m20", threadId: "t7", senderId: "u5", kind: "offer", content: `wants to claim "2018 Select Flight Invite Disc — Free to a Good Home"`, offerId: "of8", createdAt: iso(1 * DAYS) },
    { id: "m21", threadId: "t7", senderId: "u5", kind: "text", content: "Starting a college program's trophy shelf — this would be perfect for the kids.", createdAt: iso(1 * DAYS - 60_000) },
    // t8 / d8 declined
    { id: "m22", threadId: "t8", senderId: "u5", kind: "offer", content: `"Centex 2023 Tournament Disc" ⇄ "Riot 2018 Club Nationals Practice Jersey"`, offerId: "of9", createdAt: iso(10 * DAYS) },
    { id: "m23", threadId: "t8", senderId: "u1", kind: "system", content: `discwitch declined the offer. "Holding out for a jersey trade on this one, sorry!"`, createdAt: iso(9 * DAYS) },
    // t9 plain inquiry — unread by u1
    { id: "m24", threadId: "t9", senderId: "u4", kind: "text", content: "Hey! Is the matte Chain Lightning disc still around? Would you take $25 shipped?", createdAt: iso(6 * HOURS) },
    { id: "m25", threadId: "t9", senderId: "u4", kind: "text", content: "Also open to trading against my Sockeye stack if that's more your speed.", createdAt: iso(2 * HOURS) },
  ];

  // ── Ratings (real records backing recent deals) ─────────────────────────────

  const ratings: Rating[] = [
    {
      id: "rt1",
      dealId: "d4",
      fromUserId: "u2",
      toUserId: "u1",
      communication: 5,
      shippingSpeed: 5,
      itemAccuracy: 5,
      wouldTradeAgain: true,
      comment: "Shipped fast, jersey exactly as described. Textbook trade.",
      createdAt: iso(8 * DAYS),
    },
    {
      id: "rt2",
      dealId: "d5",
      fromUserId: "u3",
      toUserId: "u1",
      communication: 5,
      shippingSpeed: 4,
      itemAccuracy: 5,
      wouldTradeAgain: true,
      comment: "Paid instantly, zero drama. Good people.",
      createdAt: iso(29 * DAYS),
    },
    {
      id: "rt3",
      dealId: "d5",
      fromUserId: "u1",
      toUserId: "u3",
      communication: 4,
      shippingSpeed: 5,
      itemAccuracy: 4,
      wouldTradeAgain: true,
      comment: "Jersey had slightly more wear than the photos showed, but shipping was lightning fast.",
      createdAt: iso(29 * DAYS),
    },
  ];

  // ── Notifications ───────────────────────────────────────────────────────────

  const notifications: Notification[] = [
    { id: "n1", userId: "u1", type: "trade_proposal", title: "New trade proposal", body: `flick_therapy → "2022 Brute Squad Game Jersey — #14": "2011 UPA Club Championship Disc — Sarasota" + $15 ⇄ your jersey.`, read: false, createdAt: iso(2 * DAYS), linkTo: "/app/trades/d1" },
    { id: "n2", userId: "u1", type: "claim_request", title: "Someone wants to claim your item", body: `huck_and_pray wants to claim "2018 Select Flight Invite Disc — Free to a Good Home".`, read: false, createdAt: iso(2 * DAYS), linkTo: "/app/trades/d6" },
    { id: "n3", userId: "u1", type: "claim_request", title: "Someone wants to claim your item", body: `zone_dee wants to claim "2018 Select Flight Invite Disc — Free to a Good Home".`, read: false, createdAt: iso(1 * DAYS), linkTo: "/app/trades/d7" },
    { id: "n4", userId: "u1", type: "shipped", title: "Shipment on the way 📦", body: "sky_pilot shipped their end of the deal (tracking 9400 1108 8422 5510 3391 07).", read: false, createdAt: iso(1 * DAYS), linkTo: "/app/trades/d3" },
    { id: "n5", userId: "u1", type: "new_message", title: "Message from sky_pilot", body: "Also open to trading against my Sockeye stack if that's more your speed.", read: false, createdAt: iso(2 * HOURS), linkTo: "/app/inbox/t9" },
    { id: "n6", userId: "u1", type: "iso_match", title: "ISO match found", body: `A new jersey listing matches your wanted post: "Sockeye 2017 Nationals Jersey — Fish Scale Design".`, read: true, createdAt: iso(1 * DAYS), linkTo: "/app/listings/l11" },
    { id: "n7", userId: "u1", type: "deal_complete", title: "Deal complete 🎉", body: `Your trade of "Riot 2016 Away Jersey" is done. Leave a rating.`, read: true, createdAt: iso(8 * DAYS), linkTo: "/app/trades/d4" },
    { id: "n8", userId: "u1", type: "new_rating", title: "New rating from flick_therapy", body: `5.0 stars. "Shipped fast, jersey exactly as described. Textbook trade." Would trade again.`, read: true, createdAt: iso(8 * DAYS), linkTo: "/app/ratings" },
    { id: "n9", userId: "u2", type: "iso_match", title: "ISO match found", body: `A new jersey listing matches your wanted post: "Sockeye 2017 Nationals Jersey — Fish Scale Design".`, read: false, createdAt: iso(1 * DAYS), linkTo: "/app/listings/l11" },
    { id: "n10", userId: "u3", type: "offer_countered", title: "Counter-offer received", body: `flick_therapy countered: "Mixtape 2021 USAU Nationals Jersey" + $10 ⇄ "2011 UPA Club Championship Disc — Sarasota"`, read: false, createdAt: iso(1 * DAYS), linkTo: "/app/trades/d2" },
  ];

  return {
    v: 1,
    currentUserId: "u1",
    users,
    listings,
    isoPosts,
    deals,
    threads,
    messages,
    ratings,
    notifications,
    saves: [
      { userId: "u1", targetType: "listing", targetId: "l2", createdAt: iso(5 * DAYS) },
      { userId: "u1", targetType: "listing", targetId: "l11", createdAt: iso(20 * HOURS) },
      { userId: "u1", targetType: "iso", targetId: "iso2", createdAt: iso(4 * DAYS) },
      { userId: "u2", targetType: "listing", targetId: "l1", createdAt: iso(2 * DAYS) },
    ],
    reports: [
      {
        id: "r1",
        reporterId: "u3",
        targetType: "listing",
        targetId: "l10",
        reason: "Counterfeit or fake item",
        details:
          "\"Signed by the whole 2016 roster, no COA, trust me\" — this is almost certainly fake. Same stock photo as another listing too.",
        status: "pending",
        createdAt: iso(1 * DAYS),
      },
    ],
    blocks: [],
    activity: [
      { id: "a1", type: "new_listing", actorId: "u4", targetId: "l11", summary: `sky_pilot listed "Sockeye 2017 Nationals Jersey — Fish Scale Design"`, createdAt: iso(1 * DAYS), linkTo: "/app/listings/l11" },
      { id: "a2", type: "new_iso", actorId: "u4", targetId: "iso5", summary: "sky_pilot is hunting: ISO: Riot 2018-2020 game jerseys, size S or M…", createdAt: iso(1 * DAYS), linkTo: "/app/wanted" },
      { id: "a3", type: "new_listing", actorId: "u6", targetId: "l10", summary: `grip_it_rip_it listed "SIGNED Team USA Worlds Jersey — ultra rare!!"`, createdAt: iso(2 * DAYS), linkTo: "/app/listings/l10" },
      { id: "a4", type: "new_listing", actorId: "u1", targetId: "l9", summary: `discwitch listed "2018 Select Flight Invite Disc — Free to a Good Home"`, createdAt: iso(3 * DAYS), linkTo: "/app/listings/l9" },
      { id: "a5", type: "deal_completed", actorId: "u2", targetId: "d4", summary: `flick_therapy and discwitch completed a trade: "Riot 2016 Away Jersey"`, createdAt: iso(8 * DAYS), linkTo: "/app/listings/l15" },
      { id: "a6", type: "new_rating", actorId: "u2", targetId: "u1", summary: "flick_therapy rated discwitch 5.0★", createdAt: iso(8 * DAYS), linkTo: "/app/u/discwitch" },
      { id: "a7", type: "new_member", actorId: "u6", summary: "grip_it_rip_it joined Poachland", createdAt: iso(40 * DAYS), linkTo: "/app/u/grip_it_rip_it" },
    ],
  };
}
